// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl9wRv9Sbf8ZgdfXKCkpv2UCtTqJjMxZs',
    appId: '1:78337276689:web:5df89b311f529478b2eab0',
    messagingSenderId: '78337276689',
    projectId: 'task2-28274',
    authDomain: 'task2-28274.firebaseapp.com',
    storageBucket: 'task2-28274.appspot.com',
    measurementId: 'G-NDHNYTFSJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7-fSKc7jL8iF0wLBF-PW_CVa4S9GP4mE',
    appId: '1:78337276689:android:5bc5f1f2ef919e66b2eab0',
    messagingSenderId: '78337276689',
    projectId: 'task2-28274',
    storageBucket: 'task2-28274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIxwuHKlU2bforKTJJsxeZiouQ5BauXnY',
    appId: '1:78337276689:ios:dfa253b1081292fcb2eab0',
    messagingSenderId: '78337276689',
    projectId: 'task2-28274',
    storageBucket: 'task2-28274.appspot.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIxwuHKlU2bforKTJJsxeZiouQ5BauXnY',
    appId: '1:78337276689:ios:dfa253b1081292fcb2eab0',
    messagingSenderId: '78337276689',
    projectId: 'task2-28274',
    storageBucket: 'task2-28274.appspot.com',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl9wRv9Sbf8ZgdfXKCkpv2UCtTqJjMxZs',
    appId: '1:78337276689:web:317ce27d09a024d8b2eab0',
    messagingSenderId: '78337276689',
    projectId: 'task2-28274',
    authDomain: 'task2-28274.firebaseapp.com',
    storageBucket: 'task2-28274.appspot.com',
    measurementId: 'G-07220H05PS',
  );
}
